ekf_node:
  ros__parameters:
    use_sim_time: false
    frequency: 15.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true
    publish_acceleration: false
    predict_to_current_time: true 
    reset_on_time_jump: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # === FUENTE 1: ODOM (encoders) ===
    odom0: "/odom_raw"
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false
    predict_to_current_time: false
    # x y z R P Y  vx vy vz vR vP vY  ax ay az
    odom0_config: [true,  true,  false,
                  false, false, true,
                  true,  false, false,
                  false, false, true,
                  false, false, false]
