camera:
  camera_name: logitech_c270
  frame_id: camera_link

  camera_matrix:
    rows: 3
    cols: 3
    data: [640, 0.0, 320,
           0.0, 640, 240,
           0.0, 0.0, 1.0]

  distortion_model: "plumb_bob"

  distortion_coefficients:
    rows: 1
    cols: 5
    data: [0.0, 0.0, 0.0, 0.0, 0.0]

  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0,
           0.0, 1.0, 0.0,
           0.0, 0.0, 1.0]

  projection_matrix:
    rows: 3
    cols: 4
    data: [640, 0.0, 320, 0.0,
           0.0, 640, 240, 0.0,
           0.0, 0.0, 1.0, 0.0]

