amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "/scan"

    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    laser_model_type: "likelihood_field"
    sigma_hit: 0.2
    z_hit: 0.6
    z_rand: 0.4
    laser_min_range: 0.05
    laser_max_range: 5.0
    max_beams: 80

    min_particles: 500
    max_particles: 2000
    resample_interval: 2
    transform_tolerance: 1.0

    update_min_d: 0.05
    update_min_a: 0.10

    set_initial_pose: true
    always_reset_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0


map_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    yaml_filename: "/home/athome/mapa_solver.yaml"


planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 2.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.25
      allow_unknown: true
      use_astar: true


controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 15.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    current_goal_checker: "goal_checker"
    current_progress_checker: "progress_checker"
    controller_plugins: ["FollowPath"]
    transform_tolerance: 0.5

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10
      movement_time_allowance: 12.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.15
      stateful: false

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      max_vel_x: 0.30
      min_vel_x: 0.00
      max_vel_y: 0.0
      min_vel_y: 0.0
      max_vel_theta: 1.2
      min_speed_theta: 0.25
      min_speed_xy: 0.05
      max_speed_xy: 0.35
      trans_stopped_velocity: 0.05
      acc_lim_x: 0.60
      acc_lim_theta: 2.50

      vx_samples: 28
      vy_samples: 0
      vtheta_samples: 60
      sim_time: 0.75
      short_circuit_trajectory_evaluation: true

      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign",
                "PathAlign", "PathDist", "GoalDist", "Twirling"]

      PathAlign.scale: 40.0
      GoalAlign.scale: 10.0
      PathDist.scale: 32.0
      GoalDist.scale: 12.0
      BaseObstacle.scale: 12.0
      RotateToGoal.scale: 24.0
      Oscillation.scale: 0.5
      Twirling.scale: 1.0

      PathAlign.forward_point_distance: 0.10
      GoalAlign.forward_point_distance: 0.12

      prune_plan: true
      use_dwa: true


bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odometry/filtered"
    default_bt_xml_filename: "/home/athome/solverRos2_ws/src/solver_navigation/config/bt_trees/solver_bt.xml"
    enable_groot_monitoring: false



behavior_server:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    transform_tolerance: 0.5

    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]

    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"


global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 5.0
    transform_tolerance: 0.5
    rolling_window: false

    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        topic: "/scan"
        sensor_frame: "laser"
        clearing: true
        marking: true
        data_type: "LaserScan"
        inf_is_valid: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6


local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "odom"
    robot_base_frame: "base_link"
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    update_frequency: 10.0
    publish_frequency: 10.0
    transform_tolerance: 0.3

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        topic: "/scan"
        sensor_frame: "laser"
        clearing: true
        marking: true
        data_type: "LaserScan"
        inf_is_valid: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
